//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasLabAkhir.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int HeaderId { get; set; }
        public int RamenId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Header Header { get; set; }
        public virtual Raman Raman { get; set; }
    }
}
