CREATE TABLE [Role](
	RoleId INT PRIMARY KEY IDENTITY(1, 1),
	RoleName VARCHAR(50) NOT NULL
)

CREATE TABLE [User](
	UserId INT PRIMARY KEY IDENTITY(1, 1),
	RoleId INT NOT NULL FOREIGN KEY REFERENCES [Role](RoleId),
	UserName VARCHAR(50) NOT NULL,
	UserEmail VARCHAR(50) NOT NULL, 
	UserGender VARCHAR(50) NOT NULL,
	UserPassword VARCHAR(50) NOT NULL
)

CREATE TABLE [Header](
	HeaderId INT PRIMARY KEY IDENTITY(1, 1),
	UserId INT NOT NULL FOREIGN KEY REFERENCES [User](UserID),
	StaffId INT,
	Date DATE NOT NULL
)

CREATE TABLE [Meat](
	MeatId INT PRIMARY KEY IDENTITY(1, 1),
	MeatName VARCHAR(50) NOT NULL
)

CREATE TABLE [Ramen](
	RamenId INT PRIMARY KEY IDENTITY(1, 1),
	MeatId INT NOT NULL FOREIGN KEY REFERENCES [Meat](MeatId),
	RamenName VARCHAR(50) NOT NULL,
	Broth VARCHAR(50) NOT NULL,
	Price INT NOT NULL
)

CREATE TABLE [Detail](
	HeaderId INT NOT NULL FOREIGN KEY REFERENCES [Header](HeaderId),
	RamenId INT NOT NULL FOREIGN KEY REFERENCES [Ramen](RamenId),
	Quantity INT NOT NULL
	PRIMARY KEY (HeaderId, RamenId)
)